import { Resource, Event, Assignment, LeaderboardEntry } from '../types';

export const seedResources: Omit<Resource, 'id' | 'createdAt' | 'updatedAt' | 'createdBy'>[] = [
  {
    title: 'Hiragana Chart',
    description: 'Complete hiragana character chart with pronunciation guide',
    type: 'pdf',
    url: 'https://example.com/hiragana-chart.pdf',
    category: 'kanji',
    level: 'beginner',
  },
  {
    title: 'Basic Japanese Grammar Rules',
    description: 'Essential grammar patterns for beginners',
    type: 'text',
    content: 'Japanese grammar follows a Subject-Object-Verb (SOV) structure...',
    category: 'grammar',
    level: 'beginner',
  },
  {
    title: 'JLPT N5 Vocabulary List',
    description: 'Complete vocabulary list for JLPT N5 exam preparation',
    type: 'pdf',
    url: 'https://example.com/jlpt-n5-vocab.pdf',
    category: 'vocabulary',
    level: 'beginner',
  },
  {
    title: 'Japanese Culture: Tea Ceremony',
    description: 'Learn about the traditional Japanese tea ceremony',
    type: 'video',
    url: 'https://youtube.com/watch?v=example',
    category: 'culture',
    level: 'intermediate',
  },
  {
    title: 'Katakana Practice Sheets',
    description: 'Printable practice sheets for katakana characters',
    type: 'pdf',
    url: 'https://example.com/katakana-practice.pdf',
    category: 'kanji',
    level: 'beginner',
  },
  {
    title: 'Common Japanese Phrases',
    description: 'Essential phrases for daily conversation',
    type: 'text',
    content: 'おはようございます (Ohayou gozaimasu) - Good morning...',
    category: 'vocabulary',
    level: 'beginner',
  },
  {
    title: 'Japanese Business Etiquette',
    description: 'Professional etiquette and customs in Japanese business culture',
    type: 'video',
    url: 'https://youtube.com/watch?v=business-etiquette',
    category: 'culture',
    level: 'advanced',
  },
  {
    title: 'JLPT N3 Grammar Points',
    description: 'Advanced grammar structures for JLPT N3 level',
    type: 'text',
    content: '〜ばかり (bakari) - Only, just, nothing but...',
    category: 'grammar',
    level: 'intermediate',
  },
];

export const seedEvents: Omit<Event, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'attendees'>[] = [
  {
    title: 'Japanese Language Exchange Meetup',
    description: 'Practice Japanese with native speakers and fellow learners',
    date: new Date('2024-02-15T18:00:00'),
    location: 'Student Center Room 201',
    maxAttendees: 30,
  },
  {
    title: 'Origami Workshop',
    description: 'Learn traditional Japanese paper folding techniques',
    date: new Date('2024-02-22T15:00:00'),
    location: 'Arts Building Room 105',
    maxAttendees: 20,
  },
  {
    title: 'Anime and Manga Discussion',
    description: 'Discuss popular anime and manga while practicing Japanese',
    date: new Date('2024-03-01T19:00:00'),
    location: 'Library Conference Room',
    maxAttendees: 25,
  },
  {
    title: 'Japanese Cooking Class',
    description: 'Learn to make traditional Japanese dishes',
    date: new Date('2024-03-08T17:00:00'),
    location: 'Culinary Arts Kitchen',
    maxAttendees: 15,
  },
  {
    title: 'JLPT Study Group',
    description: 'Group study session for JLPT exam preparation',
    date: new Date('2024-03-15T16:00:00'),
    location: 'Study Hall Room 3',
    maxAttendees: 20,
  },
];

export const seedAssignments: Omit<Assignment, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'submissions'>[] = [
  {
    title: 'Hiragana Recognition Quiz',
    description: 'Test your knowledge of hiragana characters',
    instructions: 'Write the correct hiragana character for each given sound. Submit your answers as a text file.',
    dueDate: new Date('2024-02-20T23:59:00'),
    maxPoints: 50,
    type: 'text',
  },
  {
    title: 'Self-Introduction Video',
    description: 'Create a video introducing yourself in Japanese',
    instructions: 'Record a 2-3 minute video introducing yourself in Japanese. Include your name, age, hobbies, and why you\'re learning Japanese.',
    dueDate: new Date('2024-02-25T23:59:00'),
    maxPoints: 75,
    type: 'file',
  },
  {
    title: 'Japanese Culture Presentation',
    description: 'Research and present on a Japanese cultural topic',
    instructions: 'Choose a Japanese cultural topic (festivals, traditions, food, etc.) and create a 5-minute presentation. Submit your slides and script.',
    dueDate: new Date('2024-03-05T23:59:00'),
    maxPoints: 100,
    type: 'both',
  },
  {
    title: 'Grammar Exercise: Particles',
    description: 'Practice using Japanese particles correctly',
    instructions: 'Complete the particle exercises in the provided worksheet. Submit your completed worksheet as a PDF.',
    dueDate: new Date('2024-03-10T23:59:00'),
    maxPoints: 60,
    type: 'file',
  },
];

export const seedLeaderboard: Omit<LeaderboardEntry, 'id'>[] = [
  {
    studentId: 'student1',
    studentName: 'Yuki Tanaka',
    avatar: 'https://example.com/avatar1.jpg',
    points: 285,
    assignmentsCompleted: 8,
    level: 'intermediate',
    rank: 1,
  },
  {
    studentId: 'student2',
    studentName: 'Hiroshi Sato',
    avatar: 'https://example.com/avatar2.jpg',
    points: 270,
    assignmentsCompleted: 7,
    level: 'intermediate',
    rank: 2,
  },
  {
    studentId: 'student3',
    studentName: 'Aiko Nakamura',
    avatar: 'https://example.com/avatar3.jpg',
    points: 245,
    assignmentsCompleted: 6,
    level: 'beginner',
    rank: 3,
  },
  {
    studentId: 'student4',
    studentName: 'Kenji Yamamoto',
    avatar: 'https://example.com/avatar4.jpg',
    points: 220,
    assignmentsCompleted: 5,
    level: 'beginner',
    rank: 4,
  },
  {
    studentId: 'student5',
    studentName: 'Sakura Kimura',
    avatar: 'https://example.com/avatar5.jpg',
    points: 195,
    assignmentsCompleted: 4,
    level: 'beginner',
    rank: 5,
  },
  {
    studentId: 'student6',
    studentName: 'Takeshi Suzuki',
    avatar: 'https://example.com/avatar6.jpg',
    points: 180,
    assignmentsCompleted: 4,
    level: 'beginner',
    rank: 6,
  },
  {
    studentId: 'student7',
    studentName: 'Mika Ito',
    avatar: 'https://example.com/avatar7.jpg',
    points: 165,
    assignmentsCompleted: 3,
    level: 'beginner',
    rank: 7,
  },
  {
    studentId: 'student8',
    studentName: 'Ryo Takahashi',
    avatar: 'https://example.com/avatar8.jpg',
    points: 150,
    assignmentsCompleted: 3,
    level: 'beginner',
    rank: 8,
  },
];
